name: Scan
on: [push]
jobs:
  scan:
    runs-on: macOS-11
    defaults:
      run:
        shell: bash
    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      DEVELOPER_DIR: /Applications/Xcode_12.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - run: swift package resolve
      - run: bundle install
      - run: bundle exec danger
